### ISSUE TITLE
The MONAI VISTA drop-down in Monai Label plugin does not appear.

### ISSUE THREAD

**Issue by moein-shariatnia** [Project-MONAI/VISTA#10]
Thanks for sharing such an amazing model!

Just went through the steps in README, and connected to the localhost address where VISTA is running. However, I don't see the MONAI VISTA drop-down which is shown in your screenshots and where all the segmentations occur. I've updated both the 3D slicer app and the Monai Label plugin but the problem still persists.

Thank you.

**Comment by tangy5** [comment]
HI @moein-shariatnia , thanks for your interest in MONAI VISTA. The MONAI VISTA 3D slicer plugin is currently held as a separate plugin development. You will be need to manually add the plugin path with the developer mode. 

You could refer to this step:

https://github.com/Project-MONAI/VISTA#install-monai-vista-label-plugin-of-3d-slicer


Upon request, in the future, we will merge the VISTA 3D Slicer plugin with existing MONAI Label plugin and release in the 3D Slicer extension manager. Stay tuned, 

Thank you so much!

**Comment by moein-shariatnia** [comment]
Thanks for the quick response. 
I had missed that part of the setup process! Just went through the steps and it's working fine now.

Bests.

**Comment by amitjc** [comment]
> HI @moein-shariatnia , thanks for your interest in MONAI VISTA. The MONAI VISTA 3D slicer plugin is currently held as a separate plugin development. You will be need to manually add the plugin path with the developer mode.
> 
> You could refer to this step:
> 
> https://github.com/Project-MONAI/VISTA#install-monai-vista-label-plugin-of-3d-slicer
> 
> Upon request, in the future, we will merge the VISTA 3D Slicer plugin with existing MONAI Label plugin and release in the 3D Slicer extension manager. Stay tuned,
> 
> Thank you so much!

Is slicer vista plugin not available anymore? The above link only redirects to project-MONAI/Readme
