### ISSUE TITLE
CUDA out-of-memory

### ISSUE THREAD

**Issue by XuZikang** [Project-MONAI/VISTA#13]
**Describe the bug**
I deployed the VISTA on a NVIDIA 4090 GPU, and when initializing 3D embedding, I got the following error.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.92 GiB (GPU 0; 23.70 GiB total capacity; 864.09 MiB already allocated; 22.18 GiB free; 900.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I wonder how much GPU memory VISTA requires when applying SAM model? Thank you!

**Comment by tangy5** [comment]
Mostly depends on the size of your CT volume, our observation is that, 24G is good for volumes around or up to 150-200 slices. As the current pre-trained model is based on SAM with ViT-H, it's a huge model, you could try a smaller volume first. And see if it could meet your demand. 

Thank you.

**Comment by XuZikang** [comment]
Thank you! I tried to deploy it on an A800, and it cost about 40G CUDA memory, really huge : )
