### ISSUE TITLE
VISTA3D Paper Code/Info

### ISSUE THREAD

**Issue by surajpaib** [Project-MONAI/VISTA#29]
Hi Team,

I've been reading your paper on VISTA3D (https://arxiv.org/abs/2406.05285), and I'm looking to compare it with some of our work on a CT foundation model.

Initially, I assumed all reported metrics were on the corresponding test sets (when available), but I see that you have custom splits for each dataset. I also noticed that you plan to release the code and models in the future.

Do you have an estimated timeline for this release? I would appreciate any information regarding your data split strategy so we can make a direct comparison.

Thanks in advance!

**Comment by heyufan1995** [comment]
Hi:
Please check our updated repo.
Thanks
