### ISSUE TITLE
Poor Segmentation Results When Segmenting Specific Regions

### ISSUE THREAD

**Issue by VinyehShaw** [Project-MONAI/VISTA#42]
Hi there,

I’m working with chest CT images in nii.gz format and have already applied rescale "hu" preprocessing. When I run infer_everything with vista3d, the segmentation results are good, and all regions are segmented as expected. However, when I try to segment some specific regions, such as the lungs or bones, the results are almost entirely black and unusable.

Could you please help me understand why this is happening? Is there any additional preprocessing required or some parameter adjustment I might be missing?

Thanks in advance for your help.

**Comment by heyufan1995** [comment]
Hi:
I assume you are using "Kidney", "Lung", "Bone" (class index [2, 20, 21]) for indivisual class segmentation.  Those indexes are removed from training and we only use their sub-classes (left/right kidney, 5 lung lobes, 21 bone substructures). See issues https://github.com/Project-MONAI/VISTA/issues/41 

For inference,  please use the monai model zoo  https://github.com/Project-MONAI/model-zoo/tree/dev/models/vista3d which solved this problem by converting  "Kidney", "Lung", "Bone" (class index [2, 20, 21]) to their subclasses.
